### ISSUE TITLE
adding sets to the "Merkliste"

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#10]
browsing through the watcher you find products of interest - so you click the heart icon to save them in the "Merkliste"
but clicking the heart once won't add them - only by clicking again it will be added

I think this is confusing for most user if it is not one-click.
if you use it more you will know the tricks and will manage multiple lists (and deactivate the first if needed)

**Comment by dutscher** [comment]
good point. i also think about to switch the hearts into the navigation of media between images and shop link.

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/158628593-a862a773-020d-426d-8888-b51cf6dfdc54.png)
is done in last https://bbx-dutscher.vercel.app/?s=products&t=burg-blaustein
