### ISSUE TITLE
browsing through "Produkte"

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#11]
browsing through products i find it difficult to search for all sets.

looking at "Produkte" and "Status" there are 7808 entrys.
selecting "Verfügbar" shows the avialable sets and partpacks.
"Aus Performancegründen werden nur 500 von 5779 Produkte angezeigt" but there are to many.
Maybe there could be integrated a check-box integrated to hide the part packs.
And/or multiple sites to browse through all entries.

(I think) All Bluebrixx-items are sorted in 3 main categories:
Bluebrixx PRO (design cardboardbox and printed instructions) - 81 entries
Bluebrixx Specials (simple cardboardbox an digital instructions) - 1388 entries
Bluebrixx PartPacks - 6999 entries

adds up to 8468 entries is there a difference between "Tags" and "Status" entries?

**Comment by dutscher** [comment]
comming with next release!

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/158631628-32626844-b290-4bd7-8c49-b5598059d7f2.png)
done 🗡️ done
