### ISSUE TITLE
Zur Merkliste hinzufügen Kontrast in Darkmode

### ISSUE THREAD

**Issue by ingomc** [dutscher/bbx#13]
Im Darkmode ist sowohl der Text im Input für neue Liste erstellen als auch die Icons kaum erkennbar

<img width="483" alt="Bildschirmfoto 2022-03-16 um 19 40 38" src="https://user-images.githubusercontent.com/2006432/158663604-78ecb75f-67a2-48bf-a3e0-e2677255a162.png">

**Comment by rejas** [comment]
Hab ich auch schon bemerkt und n Fix in Arbeit...
