### ISSUE TITLE
Loadingspinner sollte mittig im Rahmen sein

### ISSUE THREAD

**Issue by ingomc** [dutscher/bbx#14]
Der Loadingspinner befindet sich oben links, schicker wäre komplett mittig
<img width="551" alt="Bildschirmfoto 2022-03-16 um 19 41 55" src="https://user-images.githubusercontent.com/2006432/158664078-80e8ceaf-adb7-4127-9cd4-305f7f82d0e7.png">

**Comment by dutscher** [comment]
ich fand ihn schoen da oben links. bin ich aber alleine mit der meinung :D

**Comment by rejas** [comment]
seeeeehr alleine :-)

**Comment by dutscher** [comment]
gut das ich euch habe
