### ISSUE TITLE
"Zum Shop" geht in der Default Merkliste nicht

### ISSUE THREAD

**Issue by dutscher** [dutscher/bbx#16]
Sehr merkwürdig aber wahr. In der oberen Default Merkliste lässt sich das `<a href="">...</a>` tag nicht ausführen.
In den unteren funzt es.

**Comment by rejas** [comment]
huh, very strange. seh auch keinen unterschied....

**Comment by dutscher** [comment]
done. es lag am beercss stopclick on summary von mir. ist nun per css gelöst das die default nicht schließbar ist ;)
