### ISSUE TITLE
Sonderpreise werden nicht erfasst - gar keine Preisangabe

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#17]
![Sonderpreis](https://user-images.githubusercontent.com/99642289/158762554-28bcdec9-5603-473b-885b-72e61cf6ee96.png)
Wie im Bild zu sehen, hat der Hund aktuell einen Rabatt - im Watcher wird, wohl deswegen, gar kein Preis angezeigt.

**Comment by wjdg22** [comment]
Auch sollte zwischen den Zahlen des Preises und der Währungsangabe ein Leerzeichen sein: 14,00_EUR

Links zu rabattierten Hunden:
https://www.bluebrixx.com/de/102518/Golden-Retriever-Hund
https://www.bluebrixx.com/de/102520/Bichon-Fris%C3%A9-Hund

**Comment by dutscher** [comment]
die will wohl keiner die hunde. 
ich habs den @powerdan weitergeleitet.

**Comment by dutscher** [comment]
14eur wird nun angezeigt
