### ISSUE TITLE
Gladiatoren- und Spartanerhelm

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#18]
Sind beide aus den jeweiligen Filmen:

Film: 300

https://rebrickable.com/mocs/MOC-90303/Breaaad/leonidas-i-helmet-collection/#details
https://www.bluebrixx.com/de/105133/Spartanerhelm
Spartanerhelm
Marke: BlueBrixx-Special
Hersteller-Nr: 105133
Maße (Länge x Breite x Höhe):
175 x 106 x 236 mm
Designed by Anton

https://www.imdb.com/title/tt0416449/mediaviewer/rm2487127808/?ref_=ext_shr_lnk
https://www.imdb.com/title/tt0416449/mediaviewer/rm2638122752/?ref_=ext_shr_lnk

Film: Gladiator

https://rebrickable.com/mocs/MOC-92129/Breaaad/gladiator-helmet-collection/#details
https://www.bluebrixx.com/de/105131/Gladiatorhelm
Gladiatorhelm
Marke: BlueBrixx-Special
Hersteller-Nr: 105131
Maße (Länge x Breite x Höhe):
128 x 104 x 197 mm
Designed by Anton

https://www.imdb.com/title/tt0172495/mediaviewer/rm1660916736/?ref_=ext_shr_lnk
https://www.imdb.com/title/tt0172495/mediaviewer/rm3205044224/?ref_=ext_shr_lnk

**Comment by dutscher** [comment]
und der römerhelm 105132 von asterix?
die anderen beiden sind mit aufgenommen!

**Comment by wjdg22** [comment]
Ich befürchte der Römerhelm ist parallel zum Gladiatorenhelm entstanden - es gibt keine direkte Filmreferenz
(ebenso bei der röm. Büste des MOCers die nicht bei BB erhältlich ist)

**Comment by dutscher** [comment]
dann koennen wir das hier schliessen

**Comment by wjdg22** [comment]
Es stehen zwar die Filmtitel unter beiden Setnamen - aber unter dem Tag "Film Modelle" tauchen beide bei mir nicht auf
