### ISSUE TITLE
Ansicht Produkte -> Status: alle aktiviert (nur Sets)  -  Reihenfolge bei Sortierung nach Steineanzahl falsch

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#19]
Alle sets mit allen Status anzeigen lassen und nach "Steine >" sortieren lassen.

Burg Blaustein kommt deutlich zu spät. Wohingegen der "LKW 7t gl 6x6 Autokran 4" #104597 mit 720 Teilen zu weit oben auftaucht (3. Zeile rechts).
![Reihenfolge_Steine_Absteigend](https://user-images.githubusercontent.com/99642289/158837667-c0dee1f6-1ce1-4623-a663-f32f722ca2bf.png)

**Comment by dutscher** [comment]
wird demnächst erledigt

**Comment by dutscher** [comment]
Burg Hohenzollern war das Problem mit undefined parts :)
