### ISSUE TITLE
Filter für Aktuelles

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#21]
An Tagen, wie dem Donnerstag 17.03.2022, mit vielen Einträgen im Bereich "Aktuelles" ist es schwer eine Übersicht zu erhalten.
Wäre die Filterung wie bei anderen Seite vorhanden, könnte man nach Preis / Teile sortieren und so einen besseren Eindruck bekommen, was für einen Interessant ist.

**Comment by dutscher** [comment]
zusaetzlich noch filter wie neues oder heisses produkt

**Comment by dutscher** [comment]
sortierung brauch ma hier nicht. 
![image](https://user-images.githubusercontent.com/14682/159095766-29d81099-1950-4264-a9cf-7dfd1401d421.png)
https://bbx.watch/?s=history&date=2022-03-17

**Comment by dutscher** [comment]
besteht hier noch mehr bedarf @wjdg22 ?

**Comment by wjdg22** [comment]
@dutscher es passt so - wenn nicht schieb ich den issue wieder hoch ;)
