### ISSUE TITLE
Kein Vorschaubild von neuen Ankündigungen

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#22]
Bei neuen Ankündigungen wird häufig kein Bild gezeigt - leider aber auch kein Link zur BB-Seite
![Ankuendigung_image](https://user-images.githubusercontent.com/99642289/159234888-cb5bbf96-08a0-4e8e-ad4e-7fc63253232b.PNG)

**Comment by powerdan** [comment]
Bitte einmal bis zum nächsten Zyklus warten(Alle 10 Minuten), dürfte dann behoben sein

**Comment by wjdg22** [comment]
Klappt bei mir (auch nach Neuladen der Seite) nicht.
Ist mir die Tage auch bei anderen Ankündigungen aufgefallen

![Ankuendigung_image_2](https://user-images.githubusercontent.com/99642289/159240801-00c6ce41-459c-419b-b5b5-b2262a2acca9.PNG)

**Comment by powerdan** [comment]
In der Tat, https://www.bluebrixx.com/de/animals/105142/PAN-663013-016-Meeresleben-Weisse-Haie-Delphine-Schildkroeten-Hummer-Panlos lässt den Fetch Job abstürzen. Kümmere mich drum

**Comment by powerdan** [comment]
Und 105144 hat ihn auch fertig gemacht. Ich werde für gelöschte Produkte noch was einbauen müssen. Jetzt hat er es gezogen

**Comment by wjdg22** [comment]
Liegts am letzten Eintrag im Aktuelles?
Heute hat der Bahnhof auch kein Bild...

![bahnhof ohne bild](https://user-images.githubusercontent.com/99642289/159458494-41865db5-9d6c-49ce-b0a1-7f0fb6d18ce3.PNG)

**Comment by powerdan** [comment]
Hm, das ist spannend. Ich schau mal warum er keinen Full Fetch da macht

**Comment by dutscher** [comment]
hat das produkt wirklich keine bilder?
liegt es an meinem code? :D
gruesse

**Comment by wjdg22** [comment]
Bei mir sind alle anderen Vorschaubilder nur dieses eine wird nicht gezeigt.
Set: Quantum Colony: FT-01 "Hauler"

![Quantum Colony FT-01 Hauler](https://user-images.githubusercontent.com/99642289/159897557-40ae2680-8f17-44a2-acca-fcae3bb62554.PNG)

**Comment by dutscher** [comment]
kiekste jetzt nochmal :) @powerdan hat da gestern was gefunden im uhrenwerk

**Comment by wjdg22** [comment]
Aktuell ist es bei mir erneut so, dass keine neuen Ankündigungsbilder gezeigt werden
![Ankuendigung_image_3](https://user-images.githubusercontent.com/99642289/162152642-c33830eb-b3af-409d-b915-1db99cefecfc.PNG)
![Ankuendigung_image_4](https://user-images.githubusercontent.com/99642289/162152647-a1fa8295-d6f5-46fa-a9ef-40055e3564eb.PNG)

**Comment by dutscher** [comment]
@powerdan https://api.bbx.watch/bapi/product/detail/105231 media ist leer.

**Comment by dutscher** [comment]
auch die 3 kollegen vom freitag sind noch ohne bilder
![image](https://user-images.githubusercontent.com/14682/162162372-3269b9be-f056-4f82-95e8-b884a3605c11.png)
https://bbx.watch/?s=history&date=2022-04-01

**Comment by powerdan** [comment]
Gab noch einen Fehler, sollte jetzt runder laufen

**Comment by dutscher** [comment]
Petersdom: https://api.bbx.watch/bapi/product/detail/105218
Hurde-Erweiterung für Burg Blaustein: https://api.bbx.watch/bapi/product/detail/105236

Die beiden heute Annoucten Produkte sind noch leer.

**Comment by dutscher** [comment]
@powerdan sorry das ich nerve. soll ich doch wieder nen fallback auf media einbauen?
ohne bilder sieht das murks aus.

**Comment by dutscher** [comment]
ist nun bis zu den neuen ankündigungen erstmal gelöst :)
