### ISSUE TITLE
Over scrolling Set-Beschreibung zu lang

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#23]
Bei der Ansicht "Status" -> "Verfügbar" beim durchklicken der Sets scrollt die Seite soweit, dass die Unterkante der Änderungen zu sehen ist, aber nicht mehr der Header mit Bild, Link und Beschreibung - das sollte meiner Meinung nach nicht sein - Oberkante des Kasten sollte max Oberkante Browserseite - Zeile des Setnamens sein.

Die linke Seite zeigt einen Eintrag aus Zeile 2 der gut im Bild sitzt. Klickt man auf einen der langen Einträge in der dritten Zeile scrollt meine Seite auf das linke Bild und zeigt nur den unteren Teil des Kastens mit Beschreibung und Infos.
![Scrolling_1-2](https://user-images.githubusercontent.com/99642289/159495154-21368b94-4601-4c60-ad83-e66d230e6750.png)
![Scrolling_2](https://user-images.githubusercontent.com/99642289/159496204-e75b1f6e-5fbf-418b-83e1-7a3414ecda15.png)
Passiert mir bei den 3 Feuerwehrautos und Manhatten - Kesselwagen ist kurz genug und macht keine Probleme.

**Comment by dutscher** [comment]
scrollt nun zum oberen kannte wenn es unten zu wenige sichtbar ist.
