### ISSUE TITLE
Schwarzer Hintergrund ohne Inhalte 

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#24]
Heute hatte ich mehrfache das Problem, dass zwar die Menüs geladen werden aber einfach kein Inhalt vorhanden ist.
Wobei teilweise das Menü hängt - ich kann leider nicht beurteilen wo das Problem liegt.

![20220407-Black_Konsole](https://user-images.githubusercontent.com/99642289/162263857-6a8c2cfd-0581-4443-b69f-1da83b68db02.PNG)
![20220407-Black_Seite](https://user-images.githubusercontent.com/99642289/162263861-70e4aa5c-2179-4f97-bc98-8d3ccb6fab00.PNG)

**Comment by wjdg22** [comment]
Klar 😅

**Comment by turok44** [comment]
Bei mir das gleiche Problem, es wird gar nichts mehr angezeigt, egal auf welchen Reiter ich klicke, alles leer. Schon deinstalliert,  Cache gelöscht,  nützt alles nichts😑

**Comment by dutscher** [comment]
also der "bug" ensteht durch neu angekündigte produkte in der merkliste.
der fix dafür ist schon raus. ich hatte es gerade auch in der app, dann 2mal aktualisiert und nun gehts.
wenns weiterhin nicht geht dann bitte nochmal melden.

**Comment by turok44** [comment]
Hallo. Leider bei mir immer noch der Fehler, es wird nichts mehr angezeigt, egal wie oft ich aktualisiere-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 08.04.22, 09:53 schrieb dutscher ***@***.***>:

   
  also der "bug" ensteht durch neu angekündigte produkte in der merkliste. der fix dafür ist schon raus. ich hatte es gerade auch in der app, dann 2mal aktualisiert und nun gehts. wenns weiterhin nicht geht dann bitte nochmal melden.

**Comment by turok44** [comment]
Also auch der Homescreen bleibt komplett weiß bei mir...-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 08.04.22, 09:53 schrieb dutscher ***@***.***>:

   
  also der "bug" ensteht durch neu angekündigte produkte in der merkliste. der fix dafür ist schon raus. ich hatte es gerade auch in der app, dann 2mal aktualisiert und nun gehts. wenns weiterhin nicht geht dann bitte nochmal melden.

**Comment by turok44** [comment]
Es klappt übrigens weder über die app, noch über die Seite.  Beide Wege führen zum gleichen Ergebnis, keinerlei Inhalt, nur der "Rahmen" mit den Reitern ist da. Beim wechseln der Reiter sind dann 2 markiert, erst nach Aktualisieren ist nur der zuletzt ausgewählte Reiter markiert-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 08.04.22, 09:53 schrieb dutscher ***@***.***>:

   
  also der "bug" ensteht durch neu angekündigte produkte in der merkliste. der fix dafür ist schon raus. ich hatte es gerade auch in der app, dann 2mal aktualisiert und nun gehts. wenns weiterhin nicht geht dann bitte nochmal melden.

**Comment by turok44** [comment]
> Es klappt übrigens weder über die app, noch über die Seite. Beide Wege führen zum gleichen Ergebnis, keinerlei Inhalt, nur der "Rahmen" mit den Reitern ist da. Beim wechseln der Reiter sind dann 2 markiert, erst nach Aktualisieren ist nur der zuletzt ausgewählte Reiter markiert.
Am 08.04.22, 09:53 schrieb dutscher ***@***.***>: also der "bug" ensteht durch neu angekündigte produkte in der merkliste. der fix dafür ist schon raus. ich hatte es gerade auch in der app, dann 2mal aktualisiert und nun gehts. wenns weiterhin nicht geht dann bitte nochmal melden. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by wjdg22** [comment]
Chrome/Firefox klappt wieder - nach Reload.

iOS "App" keine Chance nur durch Löschen und Neuinstallation. Danach klappts wieder.
Sämtliche Speicherleeren-Funktionen ausprobiert. Bis hin zu Geräteneustart. Weiterhin schwarz gewesen.

**Comment by turok44** [comment]
Nope, am Android Handy geht bei mir nichts, weder Browser noch app, Neuinstallation hilft auch hier nicht

**Comment by dutscher** [comment]
ohoh. bitte mehr angaben zum android gerät bitte. da hab ich wohl zuviel herum gespielt am offline modus und merklisten cloudy.
grüße

**Comment by dutscher** [comment]
das passiert tatsächlich wenn man sich die frischen ankündigungen in die merkliste holt :D
![image](https://user-images.githubusercontent.com/14682/162426943-0aa61bd5-041a-46e8-928e-ce14d9d1d666.png)
ich versuch den fehler zufinden! gebe hier gleich bescheid

**Comment by dutscher** [comment]
ein filter für noch sehr neue produkte ist nun drinnen und das rutscht dann auch wieder rein wenns verfügbar ist.
klingt sehr technisch aber ist so :D
@turok44 probier mal bitte jetzt obs wieder geht.

**Comment by dutscher** [comment]
ich konnte den fehler nachstellen und nun geht die app auch wieder mit nachgestellten fehler. sollte dann bei dir nun auch going?

**Comment by turok44** [comment]
Es geht wieder, vielen Dank!!!
