### ISSUE TITLE
Merkliste wird nicht gemerkt

### ISSUE THREAD

**Issue by turok44** [dutscher/bbx#25]
Hallo.  Bei mir verschwindet die Merkliste nach jedem neuen Aufruf der App.
Außerdem muss man öfter aktualisieren, da mit etwas angezeigt wird. 
Gruß
Tobias

**Comment by dutscher** [comment]
hallo tobias, kannst du bitte dein vorgehen näher erläutern?
beim programmier geht wie immer alles ohne probleme :D
ich bin bemüht den fehler zufinden
grüße willy

**Comment by turok44** [comment]
Hallo Willy. 
Ich nutze ein Samsung Galaxy S9. Ich gehe in die App, suche unter Produkte mein Set,  markiere das Herz.  Dann ist das Set auf der Wunschliste.  Schließe ich die app und öffne sie wieder, Merkliste leer🙈

**Comment by turok44** [comment]
Auch neu: aktualisiere ich unter Aktuelles oder Merkliste, bleibt sie Seite danach leer.  Dann muss ich 1x auf Produkte und aktualisieren, dann kann ich wieder unter jedem Reiter alles finden.

**Comment by dutscher** [comment]
ich habe paralell auf facebook einen kollegen mit dem gleichen problem.
es gibt eine rekursion bei der migration. 
ich arbeite daran!

**Comment by dutscher** [comment]
okay ich probier morgen nachmittag das ganze mal auf einem galaxy s9 nachzustellen. nutzt du den samsung browser oder den chrome? hast du die app installiert oder nutzt du die webseite? gruesse

**Comment by turok44** [comment]
Ich nutze die app

**Comment by dutscher** [comment]
https://github.com/dutscher/bbx/issues/27
wird dann wohl das gleiche wie hier sein

**Comment by dutscher** [comment]
@turok44 besteht das problem weiterhin? ich bitte dich mal die app nochmal zudeinstallieren.
ich habe leider kein glaxy s9 und die letzten probleme bei 2 benutztern lag es am cache.
grüße willy

**Comment by turok44** [comment]
Hallo. Hab gerade neu installiert und jetzt scheint alles wieder zu funktionieren😊👍🏻
