### ISSUE TITLE
Filter für letzter Artikel

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#26]
Mal so in den Raum gestellt:
Was haltet  ihr von einem "Tag" "letzter Artikel".
Ich komm jetzt drauf, da dies häufig in den letzten Tagen vorkam.
So kann man gezielt schauen was bald weg ist und sich überlegen jetzt oder warten.

Bin mir da auch nicht ganz sicher aber auf eure Kommentare gespannt.

![20220412_Letzter_Artikel](https://user-images.githubusercontent.com/99642289/162903258-c6b8cd5b-9fed-4b6d-b784-6eb32fb9e4ba.PNG)

**Comment by powerdan** [comment]
Wir bekommen die Info "letzter Artikel" leider nicht über unseren Weg. Wir müssten jedes einzelne Produkt aufrufen um festzustellen, ob es das letzte ist.

Ich glaube,BB wird das nicht so toll finden....

**Comment by dutscher** [comment]
bin ich auch der meinung. brauchen wir nicht und ist zu scraping intensiv.
