### ISSUE TITLE
Menüs vorhanden aber keine Daten

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#27]
Aktuell kann ich keine Setinfos (Daten) im Watcher sehen.
Es werden nur Menüs angezeigt.  Die kann man durchklicken aber es wird kein Inhalt angezeigt.

![20220412_Black](https://user-images.githubusercontent.com/99642289/162930627-5bc7e273-38e4-4a75-9e29-867ba7673e0e.PNG)

**Comment by dutscher** [comment]
gibts fehler in der console?

**Comment by wjdg22** [comment]
Nein. hab in 2 Browser geschaut Chrome/Firefox

**Comment by wjdg22** [comment]
habe aber nichts geändert - hatte nur "Aktuelles" offen und zum aktualisieren ein Tag zurück und wieder nach vorne

**Comment by dutscher** [comment]
nach einer remote session wurde im noCacheBuster Cache die history gelöscht.
