### ISSUE TITLE
Tag "Micro Scale" zu neuen Ankündigungen

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#28]
Die neuen Architekturmodelle benötigen noch den Tag "Micro Scale".
Vermutlich hättet ihr es eh gemacht, ist mir nur grad aufgefallen.

Markusplatz, ID: 105325
Pisa, ID: 105321

![Micro_Scale](https://user-images.githubusercontent.com/99642289/166636980-d38093bc-c457-4faf-b444-7f285dbda045.png)

**Comment by dutscher** [comment]
abjehakt!
