### ISSUE TITLE
Erstes Bild von SdKfz-263 Funkspähwagen lädt nicht

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#30]
Gesehen unter Aktuelles "Samstag 21.05.22". Beim Wechsel zu Status kann, wenn sdkfz angeklickt wurde, keine Artikelinfo mehr geöffnet werden.
Konnte aber nur teilweise reproduziert werden - kann auch sein, das es bei mir irgend wann memoryoverflow hat...
(Nach vielen anklicken unter Status)
Fehler: "uncaught (in promise) TypeError: t[2].last is undefined"

![image](https://user-images.githubusercontent.com/99642289/169672471-6bccaed5-d627-4a3c-9441-efb46c596aa5.jpeg)

**Comment by wjdg22** [comment]
Korrektur: Die nicht anzeigezeigten Infos liegen wohl nicht am SdKfz. Wenn man einfach so mehrfach Artikel unter Status anklickt geht es irgendwann nicht mehr. Getestet auf 3 PCs mit unterschiedlichen Browsern.

**Comment by dutscher** [comment]
@powerdan fehler habe ich weiter geleitet.
das erste bild vom späher liefert ein 500er.
hab den spinner nun mit einem error catcher abgefangen.

https://api.bbx.watch/bapi/product/detail/100652
https://api.bbx.watch/bapi/product/media/206

grüße
