### ISSUE TITLE
App hängt sich auf

### ISSUE THREAD

**Issue by turok44** [dutscher/bbx#31]
Moin. Sobald ich ein Produkt an klicke, hängt sich die App auf

**Comment by wjdg22** [comment]
Habs gerade 3x durchgespielt. iOS Version. wenn man wild/schnell einige Artikel in Status antippt wird der Infokasten nicht mehr angezeigt. Gleiches Problem wie beim SdKfz auch beschrieben. Problem ist aber nicht nur in Status, kann auf jeder Seite reproduziert werden.

**Comment by dutscher** [comment]
danke fuer den hinweis. schau ich mir gleich in der nachtschicht an!

**Comment by dutscher** [comment]
fehler ist gelöst. könnt ihr das mal bitte gegen checken?

**Comment by turok44** [comment]
Funktioniert wieder, danke!😊-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 24.05.22, 12:02 schrieb dutscher ***@***.***>:

   
  fehler ist gelöst. könnt ihr das mal bitte gegen checken?
