### ISSUE TITLE
Sondertag für Frankfurter Römer - oder vereint mit niederländischen zu "Hausfassaden"?

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#34]
Frankfurter Römer Hausfassade 1 - 105322
Frankfurter Römer Hausfassade 2 - 105323
Frankfurter Römer Hausfassade 3 - 105281
Frankfurter Römer Hausfassade 4 - 105282
Frankfurter Römer Hausfassade 5 - 105283
Frankfurter Römer Hausfassade 6 - 105284

**Comment by dutscher** [comment]
hausfassade 1 hat leider keine frontansicht sonst hätte ich wieder das panorama gemacht.
und da die niederländische das panorama hat hab ich beide einzeln gemacht und nicht zusammen

**Comment by wjdg22** [comment]
Doch hat sie ;)
![Frankfurter_Roemer](https://user-images.githubusercontent.com/99642289/176864699-c525b5ba-a915-4bb0-9d57-a6c80726e9c1.png)
![foto](https://user-images.githubusercontent.com/99642289/176864846-11e534f7-ff05-42af-b9ad-2875b055d224.png)


nur mal grob zusammengeschoben - aber das schaut schon sehr nach dem original aus finde ich.

**Comment by dutscher** [comment]
@powerdan 
https://bbx.watch/?s=products&t=frankfurter-roemer-hausfassade&p=105322 hier haben sich die bilder geändert
https://www.bluebrixx.com/de/105322/Frankfurter-R%C3%B6mer-Hausfassade-1
wie kann man da einen rescan anstubsen?

**Comment by dutscher** [comment]
ne ich würde nur das nehmen was auch bei bb im shop zusehen ist. das macht das scannen einfacher

**Comment by dutscher** [comment]
ich muss noch die drauf sicht pngs machen und dann ist es fertig! 
von @powerdan fehlt dann noch der rescan aber der ist für die kategorie nicht von nöten

**Comment by dutscher** [comment]
done
