### ISSUE TITLE
Gibt es Titel die Verschwunden sind?

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#35]
Habt ihr in den Daten die Möglichkeit, zu sehen ob schon einmal Artikel angekündigt waren aber dann vermutlich gecancelt wurden und einfach aus dem System genommen wurden?

**Comment by dutscher** [comment]
hast du einen verdacht?

**Comment by wjdg22** [comment]
Nein nicht konkret aber es gibt Artikel die sehr lange auf Ankündigung stehen. Da könnte ich mir schon vorstellen, dass man die doch gestoppt und vll sogar wieder rausnimmt - und wirklich auffallen würde es so gut wie keinen....

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/179225600-0eef4b83-9fae-45f9-83ab-bf2d5af07914.png)
scheint wohl keiner die email benachrichtigung zunutzen bei den produkten und somit ist das dann in der queue weiter hinten

**Comment by dutscher** [comment]
ich schließ das hier mal
