### ISSUE TITLE
Tooltip auf Mobile größer machen

### ISSUE THREAD

**Issue by rejas** [dutscher/bbx#36]
Wäre besser zu lesen und die Navigation wäre einfacher, wenn der Tooltip bei Produkten auf mobilen Endgeräten grösser wäre bzw vlt sogar die ganze Displayfläche nutzt: ![Screenshot_20220704-220448.png](https://user-images.githubusercontent.com/1313547/177211805-fc28a33c-3856-4ab0-9dcf-1fca4d1c7b11.png)

**Comment by dutscher** [comment]
das vergrößert sich mobil sogar schon, anscheind ist dein fairphone nicht mobil genug :D
ich schau mir die regel nochmal an

**Comment by dutscher** [comment]
ich habs nun mal bissi größer gemacht. tooltip breite + 200px > vw dann full breite.
haste den dom gekauft?
