### ISSUE TITLE
Datenpflege

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#37]
Film Modelle: 

Zukunftspolizei: Flugauto 105505 (ähnlich wie: Blue Runner 101005),
"Spinner" aus 
Blade Runner (1982) 

Quelle: https://en.wikipedia.org/wiki/Spinner_(Blade_Runner)

Gray Runner 105054,
"Spinner" in
Blade Runner 2049

https://www.amazon.de/CINEMACHINES-BLADE-RUNNER-SPINNER-VEHICLE/dp/B0767R1DD9
https://www.motortrend.com/news/cars-blade-runner-2049/

Soweit ich das durchschaue sind eigentlich beide Fahrzeuge "Spinner".
Hier noch 2 Quellen, das der graue auch als "Spinner" bezeichnet wird:
https://makezine.com/2020/01/09/behind-the-scenes-on-blade-runner-2049-painting-police-spinners-in-budapest/ 
https://bladerunner.fandom.com/wiki/Blade_Runner_2049

Jungel Expedition: Expeditionsbus 105533, 
"Fleetwood RV Mobile Lab" in 
Vergessene Welt: Jurassic Park (1997)

https://jurassicpark.fandom.com/wiki/Fleetwood_RV_Mobile_Lab
https://jurassic-pedia.com/mobile-lab/
https://www.imcdb.org/vehicle_24182-Fleetwood-Southwind-Storm-1996.html

Jungel Expedition: Geländewagen dreier Set 105534,
? Vergessene Welt: Jurassic Park (1997) ?
Laut den Artikel gehören zu dem Mobile Lab 2 Mercedes Benz Begleitfahrzeuge - das wird wohl einfach zusätzliches Gefährt sein...

Die Status-Anzeige überholt sich gerade selbst. Artikel, die bereits 1 Jahr + in einem Status stehen werden nun dem aktuellen Juli nicht dem vor einem Jahr zugeordnet - Vorschlag allg. Sammelpunkt  ">1 Jahr" (Auffangbecken) für alle die länger als ein Jahr warten.

**Comment by dutscher** [comment]
mach dann mal asap.

> Die Status-Anzeige überholt sich gerade selbst. Artikel, die bereits 1 Jahr + in einem Status stehen werden nun dem aktuellen > Juli nicht dem vor einem Jahr zugeordnet - Vorschlag allg. Sammelpunkt ">1 Jahr" (Auffangbecken) für alle die länger als ein > Jahr warten.

schau ich mir an

**Comment by dutscher** [comment]
@wjdg22 

> Die Status-Anzeige überholt sich gerade selbst. Artikel, die bereits 1 Jahr + in einem Status stehen werden nun dem aktuellen Juli nicht dem vor einem Jahr zugeordnet - Vorschlag allg. Sammelpunkt ">1 Jahr" (Auffangbecken) für alle die länger als ein Jahr warten.

hast du da nen beispiel?

**Comment by dutscher** [comment]
ich kann kein auffangbecken finden. bitte mach dann dazu ein neues ticket mit screenshot oder deeplink.
