### ISSUE TITLE
Auffangbecken wird zu (verstopfte) Pipeline

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#38]
Bezugnehmend auf die frühere Anmerkung:

ich fände es schade, wenn Artikel die über ein Jahr auf Ankündigung stehen nicht mehr unter "Status" eingesehen werden können.
So habe ich das mal in einem Bild gezeigt.
![fruehe_Ankuendigungen_0](https://user-images.githubusercontent.com/99642289/179542513-495de4e3-e449-488d-b07a-b5c9652fcb68.PNG)

Eventuell kann man in diesem "Auffangbecken" alles was 11+ Monate (oder 12+ M) ist sammeln. Dieses darf ruhig zugeklappt sein, um die vermutlich stetig steigende Anzahl an Artikeln nicht das letzte Jahr verdecken zulassen. Aber trotz allem können die Artikel eingesehen werden.

**Comment by dutscher** [comment]
done
