### ISSUE TITLE
Alle Marken mit aufnehmen?

### ISSUE THREAD

**Issue by dutscher** [dutscher/bbx#42]
Wange, mould king und etc mit aufnhemen?
Die Daten haben wir nur hab ich sie bisher immer rausgefiltert weil mich nur die bluebrixx produkte interessierten.

**Comment by wjdg22** [comment]
Die Menge dann ist schon gigantisch und die Aussage "alles was da war wird wieder kommen" kann dann nicht mehr zutreffen.
Da wäre ich etwas vorsichtig.
Interessant wäre es bei Bundeswehr, da hatte ichs gestern auch überlegt zu schreiben.
Der Übergang von Xingbao zu BB ist sehr fließend.

Aber die reinen Handelsprodukte sind denke ich eher von kurzer Verfügbarkeit (~1 Jahr).
Ich habt aber die Daten vll geben die auch was anderes wieder.

**Comment by dutscher** [comment]
die xingbao bluebrixx kreationen zeig ich eh schon mit an.
da ja bb über xingbao produzieren lässt ist es ja fast ihr eigenes produkt.
https://github.com/dutscher/bbx/blob/master/scripts/src/interfaces.js#L7
siehe hier.

> Ich habt aber die Daten vll geben die auch was anderes wieder.
keine lust das zu analysieren :D

dann bleiben wir bei bbx only! 
danke fürs feedback

**Comment by wjdg22** [comment]
Es gibt noch 21 weitere die dann aufm Bild als "Xingbao" (nicht BB) deklariert sind - die findet man bisher nicht im Watcher.
Meinem (Halb-)Wissen nach sind die auch alle durch die Kooperation entstanden.

Siehe hier:
https://www.bluebrixx.com/de/items?q=xingbao+bundeswehr&limit=31

Bei denen hätte ich es kurz überlegt (Funfact: Als Hersteller ist mal Xingbao mal BB eingetragen worden. Die könnten ihre Daten ruhig mal besser pflegen...) aber bleibe dabei, dass es grundsätzlich bei Fremdartikeln weniger Sinn macht.

Wobei die Benachrichtigung es ja definitiv für alle Artikel und Nutzer interessant machen würde.

Abschließend finde ich kann man wie bereits jetzt die Sachen mit BB Handschrift als Ausnahme hinzunehmen - also dann eigentlich auch die komplette Xingbao-Bundeswehrserie.

**Comment by dutscher** [comment]
hat bisher keiner danach verlangt. also weg
