### ISSUE TITLE
Bilder der Rialto werden nicht abgerufen

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#44]
Bilder der Rialto wurden nicht geladen. Klickt man vorher einen anderen Artikel an so wird dessen Bild gezeigt.

![20220825_Rialto](https://user-images.githubusercontent.com/99642289/186667745-3403d118-031c-487d-a46f-f6daa072f87f.PNG)
![20220825_Rialto-Wiesel](https://user-images.githubusercontent.com/99642289/186667748-a6d2f745-2ad6-4999-8a8d-5b380cfde541.PNG)

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/187297958-7b10b684-1420-4dfd-a07c-963b1ce69ac6.png)
https://bbx.watch/?s=products&q=rialto&p=104863

bei mir wirds angezeigt.

check mal nochmal bei dir bitte. könnte dann wenn dann an deinem cache liegen.

**Comment by wjdg22** [comment]
Bilder funktionieren - war vermutlich zu schnell geschossen. (50 sek nach Ankündigung)
