### ISSUE TITLE
Watcher bei mir auf 3 Geräten mit 4 verschiedenen Browsern nicht funktionfsfähig

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#45]
Seitenlayout wird geladen aber kein Inhalt.

bundle.js?cb=1661859467504:16 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at sd (bundle.js?cb=1661859467504:16:1018861)
    at bundle.js?cb=1661859467504:16:1211106
    at Array.map (<anonymous>)
    at bundle.js?cb=1661859467504:16:1210836
    at Object.update (bundle.js?cb=1661859467504:16:131750)
    at bundle.js?cb=1661859467504:16:1210814

**Comment by tschoiss** [comment]
Funktioniert bei mir ebenfalls auf keinem Endgerät

**Comment by wjdg22** [comment]
Geht in der Mobilapp (iOS) wieder wie es soll. (Desktop noch nicht probiert)

**Comment by dutscher** [comment]
ist geloest der problem. grund war der lucky hot pot der nun bluebrixx pro offiziell ist, hatte keine history eintraege.
falls die app immer noch nicht gehen sollte, cache leeren, aktualisieren. vorher aber die cloudid der merkliste merken ;)

gruesse

**Comment by wjdg22** [comment]
Danke!
Das es wieder läuft, mach ich hier zu.
