### ISSUE TITLE
Filmmodelle: Das fünfte Element

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#46]
Die beiden Neuankündigungen sind an die Flugfahrzeuge aus "Das fünfte Element" angelehnt.

Fliegendes Polizeiauto 105598
Flugtaxi 105597 - "Korben Dallas Taxi"

Quellen: https://de.frwiki.wiki/wiki/Le_Cinqui%C3%A8me_%C3%89l%C3%A9ment , https://www.space-figuren.de/Archiv/Flying-Cars-Diorama-The-Fifth-Element::3009.html

![20220831-Fliegendes_Polizeiauto](https://user-images.githubusercontent.com/99642289/187634999-ac98596e-9ef2-4998-8b7a-bad869908d40.PNG)
![20220831-Flugtaxi](https://user-images.githubusercontent.com/99642289/187635004-487c12b8-3dfe-4b75-8376-b02ac0e20b65.PNG)

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/188236620-6f8c7ae2-9acc-43d9-a00c-2bec170f3193.png)
danke für die vorarbeit.

https://bbx.watch/?s=products&p=105598&t=film-modelle
