### ISSUE TITLE
Filter nach Designer?

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#47]
Ich bin grad auf der Suche nach unvollständig getaggten Modellen - hier wäre der Filter nach Designer sehr hilfreich, da die meist ein Thema für sich abarbeiten. A la "Hier die Filmautos machst jetzt mal.", kurz drauf 3 zusammengehörige Filmautos...

Was denkt ihr über die Möglichkeit nach dem Designer filtern zu können?

**Comment by dutscher** [comment]
Jau hatte ich heute auch, ich pack die Designer id mit in die Datenbank und dann kannste danach filtern :)

**Comment by wjdg22** [comment]
Super, danke!

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/194728720-3ecc9c1c-6613-4283-8503-18063f4a27b9.png)

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/194781455-e28baabc-55b0-492b-8d48-682963276f01.png)
ist fertig
