### ISSUE TITLE
2 weitere Filmmodelle wollten sich verstecken

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#48]
Vermutung:

Fast & Furious
Filmautos: https://fastandfurious.fandom.com/wiki/Category:Cars

Schwarzes US-Muscle-Car = 1970 Dodge Charger R/T (https://fastandfurious.fandom.com/wiki/1970_Dodge_Charger_R/T)
105033

Japanischer Sportwagen = 1999 Nissan Skyline GT-R R34 (https://fastandfurious.fandom.com/wiki/1999_Nissan_Skyline_GT-R_R34)
105134

**Comment by dutscher** [comment]
erledigt. danke :D
