### ISSUE TITLE
Berechnungsfehler?

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#49]
Ich meine, die Zeitangabe hat einen Tag zuviel. (Erste Verfügbarkeit)
![image](https://user-images.githubusercontent.com/99642289/204105148-f6cd9014-8c39-4591-a844-46c81f183582.png)

**Comment by dutscher** [comment]
in der tat sollte es nur 22h sein. 
ich schau mal ryan :)
danke fürs finden und schön das du noch da bist.

**Comment by dutscher** [comment]
fixed
