### ISSUE TITLE
Heute wurde scheinbar das Layout der 1. Star Trek Welle in den Artikelbildern aktualisiert

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#50]
Ich fände es zwar schade die alten Bilder zu verlieren, aber die neuen sollten hier schon abgerufen werden.

**Comment by dutscher** [comment]
@powerdan 
![image](https://user-images.githubusercontent.com/14682/206319427-dd0d11f9-3e8f-42f6-9236-f1ec6908644a.png)
https://www.bluebrixx.com/de/bluebrixxspecials/104178/Star-Trek-USS-Enterprise-NCC-1701-D-BlueBrixx-Pro vs. https://bbx.watch/?s=products&p=104178

**Comment by dutscher** [comment]
@powerdan auch mehrere Part packs bekommen nen 404 auf /media

**Comment by powerdan** [comment]
Gibt jetzt die Möglichkeit im Admin UI Bilder komplett zu archivieren. Haben dann den Flag: archived: false

@dutscher Kannst du das im UI erstmal ausblenden?

**Comment by dutscher** [comment]
so das archived flag wird beachtet und die alten bilder werden erstmal ausgeblendet.
das parsen für ein star trek produkt hab ich im admin erstmal angestossen.
lets have a look

**Comment by dutscher** [comment]
wenn man den browser cache geleert hat dann gehts

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/218436622-7f81e3cb-0697-456b-8b87-1d1f280b358a.png)
