### ISSUE TITLE
Neue Ankündigung: Buggy -> Filmmodelle

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#51]
Buggy in rot mit gelben Dach
ID: 105782 

Schaut mir verdächtig nach
Bud Spencer & Terence Hill in "Zwei wie Pech und Schwefel" aus.

Modell ist ein Puma Dune Buggy

https://www.imcdb.org/vehicle_23998-Puma-Dune-Buggy-Typ-1-1972.html

**Comment by dutscher** [comment]
ist erledigt
