### ISSUE TITLE
Direktlink zeigt letzte Änderung nicht an

### ISSUE THREAD

**Issue by powerdan** [dutscher/bbx#55]
Wenn ich einen Direktlink baue wie

https://bbx.watch/?s=products&p=104876

zeigt der die letzte Änderung nicht an, ich muss erst explizit auf das Produkt klicken und sehe dann die letzte Änderung
![image](https://user-images.githubusercontent.com/389841/206136510-7c23ab0f-8d9f-4c53-b6a1-95a7529c8f43.png)
Klicke auf Produkt um es zu und wieder auf zu machen
![image](https://user-images.githubusercontent.com/389841/206136608-a32275be-1d3c-4aa3-b97a-05733e38a8ee.png)

**Comment by dutscher** [comment]
das muss ein temporärer zustand gewesen sein der nach dem cronjob parsen behoben wurde. aktuell sind alle änderungen am start
