### ISSUE TITLE
Struktur von den PartPacks aka Brickbar besser abbilden.

### ISSUE THREAD

**Issue by d0m1n1qu3** [dutscher/bbx#56]
Hi,
ich fänd es cool wenn die PartPacks besser dargestellt werden. Die üblichen Kategorien.
Evtl sogar mit import der üblichen Wishlisten.xml von Bricklink :-D
Nice wäre auch das Filtern nach Farbe ^^
vg Dominique

**Comment by dutscher** [comment]
Filter nach Farbe funzt doch, klick auf die bunten boeppel und dann siehst du nur noch deine Farbe.
Was sind die üblichen Kategorien? Ich habe die Kategorien von bluebrixx genommen und diese hat Marco erstellt der vor bluebrixx einen bricklink Store hatte.
Ein bricklink import wird schwierig weil es nicht alle Legoteile gibt und auch nicht alle bluebrixx teile korrekt benamt sind.
Hast du eine Beispiel wishlist die du hier ablegen kannst?
Bzw was ist das Ziel der wishlist?

**Comment by d0m1n1qu3** [comment]
Farbe filter bekomm ich nicht hin. Evtl seh ich den Wald auch vor lauter Bäumen nicht ;-)
ich will nicht ausschliessen das ich bbx watch einfach falsch bediene :-o :-D

Beispiel Wishliste: Ich habe bei Brick on Rails.de Anleitungen zum Bau von Eisenbahnen gekauft, bei den liegt die Bricklink Kaufliste dabei. Wenn man von den ein oder anderen Teilen aber mehrere braucht lohnt sich sowas wie Blubrixx deutlich. Stichwort: PartPacks. (die Preise in den BricklinkShops  sind auch absurt geworden) 
Derzeit versuch ich das immer manuell im Bluebrixxshop, aber die Merkliste da ist total nerfig und der Warenkorb leert sich dauernd .. Deswegen fand ich dein Ansatz hier auch cool :-) 

Aber mein grund Problem ist glaubn ich das ich irgend wie nicht weiß wie man schnell von den benötigten teilen aus der Anleitung zu einem Treffer in der Wishlist kommt.

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/214279991-86a140b3-b1c1-481a-bf6b-e7c0fa6443cb.png)
ich sehe gerade wenn man die "brickbar" aktiviert sind unten die "parts" nicht aktiviert.

**Comment by d0m1n1qu3** [comment]
Moment mal. Wo hast du denn die Brickbar her? Die ist doch genau das was ich suche :-o

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/214284112-d358f04e-cf3e-4c6e-8c12-b4ade2226ac9.png)
farblich hervorgehoben.

**Comment by dutscher** [comment]
ich brauch eine xml um zuschauen was man damit alles so anstellen kann :)
wäre ja durchaus ein cooles feature.
und auch ein befüllen des warenkorbes stand mal auf meiner liste um genau dieses leeren des warenkorbes zuumgehen welches echt uncool ist.

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/214285381-2108d862-a58f-494a-991b-cad44ffd7902.png)
 über den tag bei den parts hättest du auch zur brickbar kommen können

**Comment by d0m1n1qu3** [comment]
> ![image](https://user-images.githubusercontent.com/14682/214284112-d358f04e-cf3e-4c6e-8c12-b4ade2226ac9.png) farblich hervorgehoben.

Das hat doch nen Platz in der obersten Leiste verdient .. Da wäre ich ja nie draufgekommen .. Das is so zu sehr versteckt für Leute die das nicht kennen .. jetzt wo ich das Kenne, sind schon mal einige Punkte gelöst :-D

**Comment by dutscher** [comment]
![image](https://user-images.githubusercontent.com/14682/214286048-a72dbcdf-ce30-4c16-9fc9-fde8ae7189f3.png)
mal soll ja hier auch einwenig exploreren :D

**Comment by dutscher** [comment]
> > ![image](https://user-images.githubusercontent.com/14682/214284112-d358f04e-cf3e-4c6e-8c12-b4ade2226ac9.png) farblich hervorgehoben.
> 
> Das hat doch nen Platz in der obersten Leiste verdient .. Da wäre ich ja nie draufgekommen .. Das is so zu sehr versteckt für Leute die das nicht kennen .. jetzt wo ich das Kenne, sind schon mal einige Punkte gelöst :-D

aber ja oben ein reiter mit brickbar wäre schon nen feature worüber man nach denken könnte

**Comment by d0m1n1qu3** [comment]
> ich brauch eine xml um zuschauen was man damit alles so anstellen kann :) wäre ja durchaus ein cooles feature. und auch ein befüllen des warenkorbes stand mal auf meiner liste um genau dieses leeren des warenkorbes zuumgehen welches echt uncool ist.

guck mal hier z.B.
https://www.holgermatthes.de/bricks/data/partlists/HolgerMatthes_Teileliste_BR-80.xml
die is Frei inkl Anleitung .. die von BrickonRails kann ich dir nicht schicken, weil ja Kaufware :-o
https://www.holgermatthes.de/bricks/de/br80.php

**Comment by dutscher** [comment]
mist ich hoffte eine anleitung umsonst zubekommen :D aber ja die obrige xml reicht erstmal um etwas herum zuspielen.
mal schauen wann ich dazukomme. ein import in kombi mit merkliste erstellen wäre eine schöne funktion.

grüße willy

**Comment by d0m1n1qu3** [comment]
> > > ![image](https://user-images.githubusercontent.com/14682/214284112-d358f04e-cf3e-4c6e-8c12-b4ade2226ac9.png) farblich hervorgehoben.
> > 
> > 
> > Das hat doch nen Platz in der obersten Leiste verdient .. Da wäre ich ja nie draufgekommen .. Das is so zu sehr versteckt für Leute die das nicht kennen .. jetzt wo ich das Kenne, sind schon mal einige Punkte gelöst :-D
> 
> aber ja oben ein reiter mit brickbar wäre schon nen feature worüber man nach denken könnte

das fände ich Mega .. weil mich aus der Sicht die anderen Artikel auch nicht interessieren. also Komplette Sets usw .. Wenn man so als Moc nachbauer nach einzelteilen sucht :-D

Oder nen richtig geiles Feature wäre .. wenn das ergebnis des XML Uploads wäre, Kauf das Set x und y dann haste 90% der Teile .. weil BrickPacks sind ja manchmal aus zu Groß :-D

**Comment by dutscher** [comment]
siehe da 
![image](https://user-images.githubusercontent.com/14682/215220310-2c6fb424-eb54-4d0b-b31b-929d3cff3e69.png)
auch das url deeplinking geht nun. die brickbar unter produkte funktioniert weiterhin!
mit den import da mach ich mal ein neues issue auf

**Comment by d0m1n1qu3** [comment]
Mega. Danke. :-)
