### ISSUE TITLE
Merkliste in die Cloud geht nicht mehr

### ISSUE THREAD

**Issue by dutscher** [dutscher/bbx#57]
Mir wurde per Mail gemeldet das dies nicht mehr geht.
Der externe myjson Speicher ist Mal wieder down.
@powerdan eventuell hosten wir selber nen json storage?

**Comment by dutscher** [comment]
So funktioniert nun wieder

**Comment by wjdg22** [comment]
Habs über mehrere Geräte hinweg getestet. Klappt.
Kann man eigentlich einen Abgleich bzw. ne Info anzeigen, ob der Stand der Cloud dem angezeigten entspricht?

**Comment by dutscher** [comment]
kann man
aber wie groß ist denn deine liste bitte schön :D

**Comment by wjdg22** [comment]
Hab eine in der ich all meine Käufe tracke, eine für "zu kaufendes" und eine mit "Beobachtungen".

Und wenn ich die über Geräte hinweg gleich halten will frag ich mich manchmal, was sich eigentlich geändert hat bzw. ob ich was verloren hab (erst von der einen gelöscht aber noch nicht auf die andere Liste, nicht Gerät, verschoben)
Natürlich kann man einfach uploaden. Ist halt dann ohne Möglichkeit was nachzuvollziehen.

Wär eigentlich praktisch, wenn man sich seinen eigenen Namen erstellen kann à la "~wjdg" (statt zufällig erstellter CloudID, Tilde und dann eigengewählt 4-stellig 😅)

**Comment by dutscher** [comment]
Ich weiss was du meinst. Ich kontrolliere das nochmal aber bin der Meinung beim hinzufügen wird in die Cloud gespeichert und beim löschen auch. Nur beim öffnen der App wird nicht gesyncd. 
Es wird keine manuelle ID's geben, wenn jemand deine ID rausfindet manipuliert er deine merklisten.
Bei den generierten kann das herausfinden auch passieren aber da ist die Wahrscheinlichkeit geringer.

**Comment by dutscher** [comment]
Was hat's mit der Tilde auf sich?
