### ISSUE TITLE
Bei nur zwei Produktbildern werden die Navigationspfeile nicht gezeigt

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#59]
Gefunden bei 
Burg Bärenfels: Mauererweiterung
ID: 105654

![image](https://user-images.githubusercontent.com/99642289/215221966-0cbf18cb-8307-4661-946a-050b21ad1b96.jpeg)

![image](https://user-images.githubusercontent.com/99642289/215222313-44fcdede-13fc-459f-b1e2-ae66f85c1c36.jpeg)

**Comment by dutscher** [comment]
done
