### ISSUE TITLE
Preview picture is not shown/changed by BB

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#6]
Within the "Änderungen"-Tab the Set "Traktor mit zwei Hängern" doesn't show the preview image.
Moving the mouse will show a flickering "image not found" - icon.
![Picture_not_found](https://user-images.githubusercontent.com/99642289/154924147-4a558cc2-c0a6-4362-9b55-52aeca503850.png)

Console:
102636_1.jpg:1          GET https://www.bluebrixx.com/img/items/102/102636/300/102636_1.jpg 404 (Not Found)

Therefore this seems to be a failed link.

**Comment by dutscher** [comment]
thx, will fixxed with new api :)
