### ISSUE TITLE
"Negativ" Filter Möglichkeit

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#61]
Gibt es eine Möglichkeit, etwas "rauszufiltern".
Idee kam mir bei der Kategorie Filmmodelle. Es gibt aktuell 119 Stk. Allerdings sind 53 Stk. Star Trek Modelle.
Kann man die mit "-Star" bzw. "-Trek" verbergen? (Leider ist das so noch nicht praktikabel aber vll. habt ihr noch ne Idee.)

**Comment by dutscher** [comment]
ich hab star trek aus der kategorie genommen. da es ja klar ist das star trek nen film/serie ist und es seinen eigenen tag hat.
somit kein negativ filter notwendig!

**Comment by dutscher** [comment]
nun sinds nur noch 66 von 9146 Produkte
