### ISSUE TITLE
Neue Modelle, Infos vervollständigen

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#62]
Interstellarer Camper
106673 (Steine: 1529)
BlueBrixx-Special

-> Tag "Film Modelle" : Mel Brooks’ Spaceballs (1987)

Fahrzeug: 1986 Winnebago Chieftain
https://www.imcdb.org/vehicle_14240-Winnebago-Chieftain-1986.html

--------------------------------------------------------------------------------

U-Boot-Auto 2 in 1 Modell
106672 (Steine: 1357)
BlueBrixx-Special

-> Tag "Film Modelle" : James Bond 007 – Der Spion, der mich liebte (1977)

Fahrzeug: 1976 Lotus Esprit S1 [Type 79]
https://www.imcdb.org/vehicle_2363-Lotus-Esprit-S1-Type-79-1976.html

**Comment by dutscher** [comment]
und das expeditions mobil was ist das fürn film?
es sieht aus wie ein mercedes, zetros und arcos... finde aber keinen film dazu
die anderen beiden sind vertaggt

**Comment by wjdg22** [comment]
ich war vom Design her bei einem Mercedes Unimog 437.1 (https://de.wikipedia.org/wiki/Unimog_437.1)
Oder Mercedes Vario (https://de.wikipedia.org/wiki/Mercedes-Benz_Vario, Namen wusste ich auch nicht aber Modell hatte ich ebenfalls im Kopf, Name dann in der FB-Gruppe gelesen)

Aber ich kenn leider keinen Film der so detailliert dieses Modell ergibt (zwar ohne Tür zum Wohnraum aber egal)

**Comment by wjdg22** [comment]
![20230208](https://user-images.githubusercontent.com/99642289/217390251-86ba70c3-23a5-463b-9d0b-91297470f48b.png)

Leider ist der Film Modell Tag beim falschen vorhanden - beim richtigen hingegen nicht.

**Comment by dutscher** [comment]
done
