### ISSUE TITLE
Burg Bärenfels: Grundburg und Bergfried sind nun Bluebrixx-Pro Modelle

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#63]
Bilder müssen geupdatet werden.
Tags sollten eigentlich abgegriffen werden können oder?

Burg Bärenfels: Grundburg, 105506

Burg Bärenfels: Bergfried, 105545

**Comment by dutscher** [comment]
daniel baut gerade ne ui wo wir zudritt dann updaten können.
https://www.bluebrixx.com/de/105545/Burg-B%C3%A4renfels:-Bergfried
https://bbx.watch/?s=products&t=burg-baerenfels&p=105545

Mit den Tags muss ich mal schauen. Das wird sich ja dann auf die Erweiterungen auch ausweitern.

**Comment by dutscher** [comment]
Tags sind erledigt! Bilder gibt uns @powerdan dann bescheid

**Comment by dutscher** [comment]
bilder sind aktuell
