### ISSUE TITLE
Hat sich das Produktbild verirrt?

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#65]
Star Trek Gemälde in Picards Bereitschaftsraum
ID: 105420

Bei diesem Artikel hängt glaub ich das Bild fest.

**Comment by dutscher** [comment]
ich habs mal angestossen

**Comment by dutscher** [comment]
@wjdg22 hierfür bitte das reset tag nutzen und ich hab dir per signal geschrieben

**Comment by wjdg22** [comment]
Ich würde behaupte, sowohl du als auch ich haben noch versucht via "reset" diesen Issue zu beheben - scheint aber nicht zu klappen?

**Comment by dutscher** [comment]
@powerdan https://api.bbx.watch/bapi/product/detail/105420 jap weiterhin ist media leer.
im admin haben wir reset gedrückt wie jakob sagte

**Comment by powerdan** [comment]
Jetzt sollte es passen, der cache war zu hartnäckig

**Comment by dutscher** [comment]
funzt thx
