### ISSUE TITLE
Neue Vögel -> Tag: Tier ergänzen & teilweise Bildfehler

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#67]
| ID | Name | Bildfehler |
| --- | --- | --- |
| 106706 | Mäusebussard | ja |
| 106708 | Specht | nein |
| 106709 | Elster | ja |
| 106710 | Rotkehlchen | nein |
| 106714 | Sperling | ja |
| 106718 | Bachstelze | ja |

**Comment by dutscher** [comment]
@powerdan hab ich dir schon gemeldet

**Comment by powerdan** [comment]
Jetzt sollte es passen, der cache war zu hartnäckig, bitte um retest

**Comment by dutscher** [comment]
done
