### ISSUE TITLE
105420 - Star Trek Gemälde in Picards Bereitschaftsraum - nicht im Tag "Star Trek"

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#69]

**Comment by dutscher** [comment]
liegt wahrscheinlich daran weils zu neu ist.

**Comment by wjdg22** [comment]
Könnte auch durch "Bild" ergänzt werden.
kann man die Issues pausieren?

**Comment by dutscher** [comment]
das ist ein manuelles tagging das führe ich gleich mal durch

**Comment by dutscher** [comment]
done
