### ISSUE TITLE
additional information for Science-Fiction gepanzerter Mannschaftstransporter (APC)

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#7]
https://www.bluebrixx.com/de/neuheiten/104614/Science-Fiction-gepanzerter-Mannschaftstransporter-APC-BlueBrixx-Special
>>>
Science-Fiction gepanzerter Mannschaftstransporter (APC)
Gepanzerter Truppentransporter, inklusive eines Standgeschütztes

Maßstab 1:18
Marke: BlueBrixx-Special
Hersteller-Nr: 104614
Maße (Länge x Breite x Höhe):
235 x 110 x 90 mm
<<<

this Set should be tagged as a movie model. see Link below:

https://avp.fandom.com/wiki/M577_Armored_Personnel_Carrier

**Comment by dutscher** [comment]
done
