### ISSUE TITLE
Monstertruck dunkelblau

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#70]
https://bbx.watch/?s=products&q=105135&p=105135

das letzte Bild war meine ich, ein Blick in den Innenraum Richtung Lenkrad. Aktuell wird es bei mir als Bildfehler angezeigt.
Mittlerweile verlinken Bluebrixx aber auch ein Video - sollte das nicht angezeigt werden?

Was macht der "Reset" Button in Mod-Umgebung?
Hatte das erneut versucht.

**Comment by dutscher** [comment]
mal davon abgesehen das der monstertruck demnächst bei mir eintrudelt :) 
kann ich dir deine frage nicht beantworten.

@powerdan funzt der reset button bei jakob überhaupt?
ich hatte auch noch nicht das gefühl das er bei mir funzt.

grüße

**Comment by dutscher** [comment]
Going now
