### ISSUE TITLE
Keine Anzeige mehr

### ISSUE THREAD

**Issue by AtomicRazor** [dutscher/bbx#73]
Mooin, egal auf welchem Gerät ich schaue, überall wird mir nichts mehr Angezeigt auf der Seite nur noch das HUD.
![Bild_2023-04-15_095307061](https://user-images.githubusercontent.com/130827287/232197435-7b9ca41c-e7a1-4778-9625-45c56a71e650.png)

**Comment by dutscher** [comment]
Hey atomic razor :)
den Fehler hab ich verursacht, ich bin gerade im Urlaub und da hat der fix jetzt mal nen Tag gedauert.

Aber keine Angst nun gehts wieder.

Danke fürs melden!
