### ISSUE TITLE
Frage nach Bilder Reset

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#76]
105084 | Burg Hohenzollern

Bei der Burg wurde nur das damalige Ankündigungsfoto gezeigt.
Ich hab nun "Reset" gedrückt - die neuen Produktbilder sind da.

Aber wir als Ankündigung seit einem Tag geführt.

![image](https://github.com/dutscher/bbx/assets/99642289/255f5eaa-5e0e-484b-8022-05aa58a8e76a)

**Comment by dutscher** [comment]
der bug ist wahrscheinlich weils kein vergleichsdatum gibt. schau ich mir mal an

**Comment by dutscher** [comment]
ist gelöst. zeigt nun das jahr noch zusätzlich an und es war älter als ein jahr mit nur einen eintrag.
problem gelöst :D
