### ISSUE TITLE
neues Modell "futuristisches rotes Motorrad" 107192

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#77]
Dieses Motorrad ist ein Filmmodell.
Entstammt einem Manga names "Akira" (Wiki-Akira-Franchise-Link: https://en.wikipedia.org/wiki/Akira_(franchise))
Das Motorrad an sich ist wohl "(Shotaro) Kaneda's Bike" (https://akira.fandom.com/wiki/Shotaro_Kaneda%27s_Bike)

![20230614-Akira](https://github.com/dutscher/bbx/assets/99642289/40286e59-7840-4f6e-9b26-921a7d5272f2)
Vorschlag:
futuristisches rotes Motorrad
Akira - Shotaro Kaneda's Bike

![image](https://github.com/dutscher/bbx/assets/99642289/6c9b4dc8-5e73-47aa-ac35-c19ceb893df0)

Bug-Beschreibung:
Wenn ich nach der ID suche finde ich den Artikel nicht. Nur über "Ankündigungen"

Nakatomi Plaza ist zur gleichen Zeit angekündigt worden, hat die ID:107190.
Sucht man nun nach "10719" findet man nur Nakatomi Plaza obwohl "107192" - Motorrad auch gefunden werden sollte.

**Comment by dutscher** [comment]
wird sich angeguckt!

**Comment by dutscher** [comment]
film modelle tag ist auch am start

**Comment by dutscher** [comment]
mail an bluebrixx ist raus.

**Comment by dutscher** [comment]
es bleibt bei ales https://www.bluebrixx.com/de/bluebrixxspecials/107192/Futuristisches-Rotes-Motorad-BlueBrixx-Special
