### ISSUE TITLE
BBX.Watch V2 - Preview of "Gorch Fock" picture isnt shown

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#8]
https://www.bluebrixx.com/de/104471/Gorch-Fock?

In the testing of the Version 2 of the Watcher:
Under the Tab "Aktuelles" is the new Set "Gorch Fock" listed.
The Preview Image isnt shown. Unlike the approved Watcher (V1) there can be seen the right image.
But klicking on the "Gorch Fock" doesnt produce any failure in the console.

**Comment by dutscher** [comment]
new api did not parsed yet the media https://api.bbx.watch/bapi/product/detail/104471

https://bbx-dutscher.vercel.app/?product=104471&page=history

cheers

**Comment by dutscher** [comment]
images for new announced image are now stable there.
