### ISSUE TITLE
Futuristischer Belagerungspanzer 107181

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#80]
Ist dem Spiel Starcraft II entliehen - würde das in die Film-Modelle eingruppieren

Futuristischer Belagerungspanzer 
Hersteller-Nr: 107181

Starcraft II - Terran Siege Tank

Terran ist die Rasse (Mensch)
Belagerungspanzer

![image](https://github.com/dutscher/bbx/assets/99642289/87b05ff7-73a8-439a-9c30-8bebafbe160e)
![image](https://github.com/dutscher/bbx/assets/99642289/f7454a44-0c0a-4790-b053-25ed4cfcb56e)
(Quellen:
https://static.wikia.nocookie.net/starcraft/images/0/0e/SiegeTank_SC2-WoL_Story1.jpg/revision/latest?cb=20100820025434
https://starcraft.fandom.com/wiki/Siege_tank
https://www.bluebrixx.com/img/items/107/107181/1000/107181_4.jpg <- gespiegelt)

Ingame Starcraft 2:
![image](https://github.com/dutscher/bbx/assets/99642289/57d12776-abb7-489e-96d3-e0875e240174)
https://youtu.be/XnU5eYkCCAo?si=2iG-Ob6cJPGb9H3f&t=751

STARCRAFT REMASTERED Trailer 14.08.2017:
![image](https://github.com/dutscher/bbx/assets/99642289/797ecf42-3910-4262-8561-f051b78fbc67)
https://youtu.be/c24mzfsHXAo?si=ZZnOFiY5JqCuKHuU&t=74

**Comment by dutscher** [comment]
nice! danke dir "Diorama: dreibeiniger Weltenzerstörer" hab ich mal noch "Krieg der Welten" hinzugefügt
