### ISSUE TITLE
Ausgelistete Teile in neue Kategorie und nicht nur auf "rot"

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#81]
![image](https://github.com/dutscher/bbx/assets/99642289/53956661-e498-4758-a5d4-008961defb63)
Dieses Set findet sich nicht mehr im BB-Onlinestore.

War wohl dieses Objekt:
![image](https://github.com/dutscher/bbx/assets/99642289/cea57305-7053-4de2-8fe0-db70d7f66d77)
(https://youtu.be/vXZKHmi5AS8?si=kEj1y1nlR4LJlBGq&t=356)

Macht es Sinn nun also diese ausgelisteten Sets in eine eigene Kategorie zu packen.
Vielleicht sogar ohne andere Tags? Bzw. zur besseren Erkennbarkeit gar eine neue Farbe einführen? (Grau)
![image](https://github.com/dutscher/bbx/assets/99642289/34bf4f57-4181-4520-adc3-e55f6e375132)

**Comment by wjdg22** [comment]
Ich meine, mich zu erinnern, dass Neuschwanstein 1 auch nicht mehr kommt - dafür ja die zweite Version von Xingbao.
![image](https://github.com/dutscher/bbx/assets/99642289/3cd8b447-92a1-4f68-8488-d445971afd9e)

Der hier ist auch raus:
![image](https://github.com/dutscher/bbx/assets/99642289/f2900e32-2389-4cc0-bae5-8b59d1747f68)
Bei dem fiel mir noch auf, dass zwar 2021 als Jahreszahl eingepflegt wird aber das 2022 nicht.
Ja mir ist bewusst, dass es 2023 noch keinen 17.12. gab - fürs schnelle lesen wärs meiner Meinung nachangenehm "--- 2022 ---" drüber stehen zuhaben, da wir ja in 2023 sind.

**Comment by dutscher** [comment]
![image](https://github.com/dutscher/bbx/assets/14682/07561a09-6314-48d1-bed9-bbf9082ba6a6)
die jahreszahl steht nun am anfang
anstatt eine neue farbe einzuführen habe ich die produkte gelöscht.
danke fürs finden!
öffne das hier wieder wenn du neue findest.

**Comment by wjdg22** [comment]
100652
100657
101036
101040
101041
101061
101062
101063
101064
101069
101070
101071
101072
101859
101863
101866
101881
104309
104419
400002
400003
400005
400006
400008
400009
400011
400012
400014
400015
401170
401171
401290
800001

**Comment by dutscher** [comment]
oh noooooo

**Comment by dutscher** [comment]
![image](https://github.com/dutscher/bbx/assets/14682/0520bd91-50b6-4934-a97f-4c32ab2a9ae8)
