### ISSUE TITLE
Einige Artikel weisen keinen Link zur Anleitung auf

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#83]
Beispiele:
106850, Kompaktes Carbio 2 in 1
![image](https://github.com/dutscher/bbx/assets/99642289/5a4f7960-1807-4d58-abbf-a5c9e5cbf33a)

106558, Feuerwehr Mehrzweckfahrzeug mit verschiedenen Aufbauten
![image](https://github.com/dutscher/bbx/assets/99642289/81c4d605-aa80-4898-8589-664021761ff5)

105786, Mittelalterlicher Stallmeister
![image](https://github.com/dutscher/bbx/assets/99642289/8abfa96b-b399-4120-a38b-9ff2ab43d2c5)

106971, Rettungsshuttle
![image](https://github.com/dutscher/bbx/assets/99642289/3c543d5b-a59a-4a4a-82d8-765519ad0f4f)

Meine Vermutung wäre, dass das alles Artikel sind, die erstmalig lieferbar sind (ab einem gewissen Datum X). Wohl ab Juli, ich hoff du kannst das schneller ausm System ziehen - wollte ne Liste zusammenschreiben, aber das sind zu viele Sets...

Achtung: Betrifft auch Sperling (106714) und Bachstelze (106718) diese sind nicht mehr als "Neu" gekennzeichnet, da sie am Erscheinungstag kurze Zeit "Bald erhältlich" waren.

Zusatz:
Bei manchen steht "Download" bei anderen eine Dateigröße:
![image](https://github.com/dutscher/bbx/assets/99642289/d3607d80-1459-4c9b-abcd-c1e14fbc6cf6) ![image](https://github.com/dutscher/bbx/assets/99642289/f3f9d05e-e0c1-478f-ae34-a151c5a3f5c7)

Hat keine Anleitung, ist Fremdprodukt von ZHE GAO
106867, weiße Chrysantheme
![image](https://github.com/dutscher/bbx/assets/99642289/e8c4c94c-71c4-4d4e-bfe3-407de863d683)

**Comment by dutscher** [comment]
der anleitungs import ist ein manueller prozess wegen der anmeldung der /inst seite.
das manchmal mb da steht liegt daran das bluebrixx die angabe im pdf datei namen angegeben hat.
zegao produkt wird gelöscht :)

**Comment by dutscher** [comment]
hier es sind einige anleitungen dazu gekommen :) 
https://github.com/dutscher/bbx/commit/766d9022635577a9a1eb35e2bbb05bfc05ff7fc5
