### ISSUE TITLE
Set 107452 nicht im System - Reobrix Mittelalterliche Stadt Taverne

### ISSUE THREAD

**Issue by skyrahfall** [dutscher/bbx#88]
Hi,

gerade zufällig gesehen unter den Neuheiten bei BB:

https://www.bluebrixx.com/de/knights/107452/REO-66017-Mittelalterliche-Stadt-Taverne-Reobrix

Mist weder über die SetNr 107452 noch über den Suchbegriff Taverne auffindbar.
Auch unter „Status“ wird es nicht aufgelistet.

Vielen Dank für das tolle Projekt
und viele Grüße

**Comment by skyrahfall** [comment]
Wenn ich durch den Code schaue, dann sehe ich in der data/data.json folgende Kateogrie:
"https://www.bluebrixx.com/de/bluebrixxspecials/knights",

da ist das Set nicht drin, da kein BB Special.
Es gibt noch die Links zu „Themen“
https://www.bluebrixx.com/de/themen/knights

Da wäre es drin. Falls Ihr nur die reinen BB Sachen  parsen wollt, könnt Ihr das Ticket natürlich gerne schließen.

VG

**Comment by dutscher** [comment]
wir haben ausschließlich bluebrixx produkte geparsed :)
