### ISSUE TITLE
BBX Watcher V2 - hovering mousecursor over the set-image will show "klicking hand"

### ISSUE THREAD

**Issue by wjdg22** [dutscher/bbx#9]
But there is no Link to click - only if you hover over "zum Shop" the clicking will have the action to open the desired Link.
 (can be seen by the lower left corner - no link - clickable link shown)

![Cursorchange](https://user-images.githubusercontent.com/99642289/157390606-cf4f6ae4-8248-4b95-83e9-c20789c52f1a.png)

Maybe the is a way to clearify when the link will open. Like a outline for "zum Shop" - i know its not good looking... or more dominant shadow.

**Comment by dutscher** [comment]
i will do a dark shadow on the bottom of the image placeholder to clearify the link.
![image](https://user-images.githubusercontent.com/14682/157404038-db01bcab-bccc-4283-a6f9-1932aa4f67e7.png)
cheers

**Comment by dutscher** [comment]
solved with fade gradient
